#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

sudo apt install git inkscape libgtk-3-dev autoconf zsh tmux curl composer fonts-powerline gtk2-engines-murrine
sudo apt install moka-icon-theme faba-icon-theme

# arc flatabulous theme
wget http://launchpadlibrarian.net/365856925/multiarch-support_2.27-3ubuntu1_amd64.deb \
    && wget http://launchpadlibrarian.net/353281752/libsass0_3.4.8-1_amd64.deb \
    && wget http://launchpadlibrarian.net/344203197/sassc_3.4.5-1_amd64.deb \
    && sudo dpkg -i multiarch-support_2.27-3ubuntu1_amd64.deb \
    && sudo dpkg -i libsass0_3.4.8-1_amd64.deb \
    && sudo dpkg -i sassc_3.4.5-1_amd64.deb

# oh-my-zsh
sudo rm -r ~/.oh-my-zsh \
    && sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
    && git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# docker && docker compose
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo apt-key fingerprint 0EBFCD88

sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io
sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

sudo snap install slack
sudo snap install phpstorm

# dotbot
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

rm multiarch-support_2.27-3ubuntu1_amd64.deb libsass0_3.4.8-1_amd64.deb sassc_3.4.5-1_amd64.deb